// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String color;
float humidity;
float lux_n;
float soil_moisture_n;
float temperature;

void initProperties(){

  ArduinoCloud.addProperty(color, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(lux_n, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(soil_moisture_n, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
